name: CI

# Define os eventos que acionam o workflow
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
    # Job para executar os testes do projeto
  test:
    name: QA Tests
    runs-on: ubuntu-latest
    services:
      # Define o Redis como serviço para os testes
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test ./test/...
